### ISSUE TITLE
Issue on page: Storage and Interfaces

### ISSUE THREAD

**Issue by rwwh** [GenomicDataInfrastructure/oneplusmg-framework#6]
I would like to report an issue on the Storage and Interfaces page at `/storage-and-interfaces`. Description of the issue:

Link from "FEGA technologies" to https://web2.ega-archive.org/federated is redirected to https://ega-archive.org/federated and there results in a 404.

**Comment by MKonopkoELIXIR** [comment]
This seems to work on my system, can you check it again?  Maybe the website had been down.

**Comment by rwwh** [comment]
Yup works now.
